import { e_megalo_sound } from "@blamnetwork/blf/haloreach/v11860_10_07_24_0147_omaha_release";
import {
  MegaloSound,
  type MegaloSound as MegaloSoundName,
} from "src/frontend/intermediate-representation/game/megalogamengine/megalogamengine_sounds";
import { mapMegaloEnum } from "src/frontend/intermediate-representation/megaloEnum";

const MEGALO_SOUND_TO_BLF = {
  [MegaloSound.none]: e_megalo_sound.none,
  [MegaloSound.slayer]: e_megalo_sound.slayer,
  [MegaloSound.ctf]: e_megalo_sound.ctf,
  [MegaloSound.flag_captured]: e_megalo_sound.flag_captured,
  [MegaloSound.flag_dropped]: e_megalo_sound.flag_dropped,
  [MegaloSound.flag_recovered]: e_megalo_sound.flag_recovered,
  [MegaloSound.flag_reset]: e_megalo_sound.flag_reset,
  [MegaloSound.flag_stolen]: e_megalo_sound.flag_stolen,
  [MegaloSound.flag_taken]: e_megalo_sound.flag_taken,
  [MegaloSound.vip]: e_megalo_sound.vip,
  [MegaloSound.new_vip]: e_megalo_sound.new_vip,
  [MegaloSound.vip_killed]: e_megalo_sound.vip_killed,
  [MegaloSound.juggernaut]: e_megalo_sound.juggernaut,
  [MegaloSound.new_juggernaut]: e_megalo_sound.new_juggernaut,
  [MegaloSound.territories]: e_megalo_sound.territories,
  [MegaloSound.territory_captured]: e_megalo_sound.territory_captured,
  [MegaloSound.territory_lost]: e_megalo_sound.territory_lost,
  [MegaloSound.assault]: e_megalo_sound.assault,
  [MegaloSound.bomb_armed]: e_megalo_sound.bomb_armed,
  [MegaloSound.bomb_detonated]: e_megalo_sound.bomb_detonated,
  [MegaloSound.bomb_disarmed]: e_megalo_sound.bomb_disarmed,
  [MegaloSound.bomb_dropped]: e_megalo_sound.bomb_dropped,
  [MegaloSound.bomb_reset]: e_megalo_sound.bomb_reset,
  [MegaloSound.bomb_returned]: e_megalo_sound.bomb_returned,
  [MegaloSound.bomb_taken]: e_megalo_sound.bomb_taken,
  [MegaloSound.infection]: e_megalo_sound.infection,
  [MegaloSound.infected]: e_megalo_sound.infected,
  [MegaloSound.last_man_standing]: e_megalo_sound.last_man_standing,
  [MegaloSound.new_zombie]: e_megalo_sound.new_zombie,
  [MegaloSound.oddball]: e_megalo_sound.oddball,
  [MegaloSound.ball_spawned]: e_megalo_sound.ball_spawned,
  [MegaloSound.ball_taken]: e_megalo_sound.ball_taken,
  [MegaloSound.ball_dropped]: e_megalo_sound.ball_dropped,
  [MegaloSound.ball_reset]: e_megalo_sound.ball_reset,
  [MegaloSound.king]: e_megalo_sound.king,
  [MegaloSound.hill_controlled]: e_megalo_sound.hill_controlled,
  [MegaloSound.hill_contested]: e_megalo_sound.hill_contested,
  [MegaloSound.hill_moved]: e_megalo_sound.hill_moved,
  [MegaloSound.headhunter]: e_megalo_sound.headhunter,
  [MegaloSound.stockpile]: e_megalo_sound.stockpile,
  [MegaloSound.race]: e_megalo_sound.race,
  [MegaloSound.defense]: e_megalo_sound.defense,
  [MegaloSound.offense]: e_megalo_sound.offense,
  [MegaloSound.destination_moved]: e_megalo_sound.destination_moved,
  [MegaloSound.generator_armed]: e_megalo_sound.generator_armed,
  [MegaloSound.core_armed]: e_megalo_sound.core_armed,
  [MegaloSound.generator_disarmed]: e_megalo_sound.generator_disarmed,
  [MegaloSound.core_disarmed]: e_megalo_sound.core_disarmed,
  [MegaloSound.sudden_death]: e_megalo_sound.sudden_death,
  [MegaloSound.game_over]: e_megalo_sound.game_over,
  [MegaloSound.bone_cv_defeat]: e_megalo_sound.bone_cv_defeat,
  [MegaloSound.bone_cv_ph1_defeat]: e_megalo_sound.bone_cv_ph1_defeat,
  [MegaloSound.bone_cv_ph1_intro]: e_megalo_sound.bone_cv_ph1_intro,
  [MegaloSound.bone_cv_ph1_victory]: e_megalo_sound.bone_cv_ph1_victory,
  [MegaloSound.bone_cv_ph2_defeat]: e_megalo_sound.bone_cv_ph2_defeat,
  [MegaloSound.bone_cv_ph2_victory]: e_megalo_sound.bone_cv_ph2_victory,
  [MegaloSound.bone_cv_ph3_victory]: e_megalo_sound.bone_cv_ph3_victory,
  [MegaloSound.bone_cv_victory]: e_megalo_sound.bone_cv_victory,
  [MegaloSound.bone_sp_defeat]: e_megalo_sound.bone_sp_defeat,
  [MegaloSound.bone_sp_ph1_intro]: e_megalo_sound.bone_sp_ph1_intro,
  [MegaloSound.bone_sp_ph1_victory]: e_megalo_sound.bone_sp_ph1_victory,
  [MegaloSound.bone_sp_ph2_intro]: e_megalo_sound.bone_sp_ph2_intro,
  [MegaloSound.bone_sp_ph2_victory]: e_megalo_sound.bone_sp_ph2_victory,
  [MegaloSound.bone_sp_ph3_intro]: e_megalo_sound.bone_sp_ph3_intro,
  [MegaloSound.bone_sp_ph3_victory]: e_megalo_sound.bone_sp_ph3_victory,
  [MegaloSound.isle_cv_defeat]: e_megalo_sound.isle_cv_defeat,
  [MegaloSound.isle_cv_ph1_defeat]: e_megalo_sound.isle_cv_ph1_defeat,
  [MegaloSound.isle_cv_ph1_intro]: e_megalo_sound.isle_cv_ph1_intro,
  [MegaloSound.isle_cv_ph2_intro]: e_megalo_sound.isle_cv_ph2_intro,
  [MegaloSound.isle_cv_ph2_victory]: e_megalo_sound.isle_cv_ph2_victory,
  [MegaloSound.isle_cv_ph3_intro]: e_megalo_sound.isle_cv_ph3_intro,
  [MegaloSound.isle_cv_ph3_victory]: e_megalo_sound.isle_cv_ph3_victory,
  [MegaloSound.isle_sp_defeat]: e_megalo_sound.isle_sp_defeat,
  [MegaloSound.isle_sp_ph1_defeat]: e_megalo_sound.isle_sp_ph1_defeat,
  [MegaloSound.isle_sp_ph1_extra]: e_megalo_sound.isle_sp_ph1_extra,
  [MegaloSound.isle_sp_ph1_intro]: e_megalo_sound.isle_sp_ph1_intro,
  [MegaloSound.isle_sp_ph1_victory]: e_megalo_sound.isle_sp_ph1_victory,
  [MegaloSound.isle_sp_ph2_defeat]: e_megalo_sound.isle_sp_ph2_defeat,
  [MegaloSound.isle_sp_ph2_victory]: e_megalo_sound.isle_sp_ph2_victory,
  [MegaloSound.isle_sp_ph3_victory]: e_megalo_sound.isle_sp_ph3_victory,
  [MegaloSound.isle_sp_victory]: e_megalo_sound.isle_sp_victory,
  [MegaloSound.bone_sp_ph3_defeat]: e_megalo_sound.bone_sp_ph3_defeat,
  [MegaloSound.isle_cv_ph3_defeat]: e_megalo_sound.isle_cv_ph3_defeat,
  [MegaloSound.covy_big_win]: e_megalo_sound.covy_big_win,
  [MegaloSound.covy_win1]: e_megalo_sound.covy_win1,
  [MegaloSound.covy_win2]: e_megalo_sound.covy_win2,
  [MegaloSound.invasion_beginning]: e_megalo_sound.invasion_beginning,
  [MegaloSound.unsc_big_win]: e_megalo_sound.unsc_big_win,
  [MegaloSound.unsc_win1]: e_megalo_sound.unsc_win1,
  [MegaloSound.unsc_win2]: e_megalo_sound.unsc_win2,
  [MegaloSound.power_down]: e_megalo_sound.power_down,
  [MegaloSound.reinforcements]: e_megalo_sound.reinforcements,
  [MegaloSound.respawn_tick]: e_megalo_sound.respawn_tick,
  [MegaloSound.alpha_under_attack]: e_megalo_sound.alpha_under_attack,
  [MegaloSound.bravo_under_attack]: e_megalo_sound.bravo_under_attack,
  [MegaloSound.charlie_under_attack]: e_megalo_sound.charlie_under_attack,
} as const satisfies Record<MegaloSoundName, e_megalo_sound>;

export const encodeMegaloSound = (value: MegaloSoundName): e_megalo_sound =>
  mapMegaloEnum(value, MEGALO_SOUND_TO_BLF);
