import type {
  CompilerCapabilities,
  ToCapabilities,
} from "src/backend/compile/diagnostics/assertCompatibleIR";
import type { PlayerTraits } from "src/frontend/intermediate-representation/game/game_engine_player_traits";

const CAPABILITIES_73_PLAYER_TRAITS = {
  shieldVitality: {
    damageResistancePercentage: true,
    bodyMultiplierPercentage: true,
    bodyRechargeRatePercentage: true,
    shieldMultiplierPercentage: true,
    shieldRechargeRatePercentage: true,
    headshotImmunity: true,
    vampirismPercentage: true,
    assasinationImmunity: true,
    deathless: true,
  },
  weapons: {
    damageModifierPercentageSetting: true,
    meleeDamageModifierPercentageSetting: true,
    initialPrimaryWeaponAbsoluteIndex: true,
    initialSecondaryWeaponAbsoluteIndex: true,
    initialGrenadeCount: true,
    rechargingGrenades: true,
    infiniteAmmo: true,
    weaponPickup: true,
    equipmentUsage: true,
    dropEquipment: true,
    infiniteEquipment: true,
    initialEquipmentAbsoluteIndex: true,
  },
  movement: {
    speedPercentage: true,
    gravityPercentage: true,
    vehicleUsage: true,
    jumpModifier: true,
    sprinting: true,
    doubleJump: true,
  },
  appearance: {
    activeCamo: true,
    waypoint: true,
    gamertag: true,
    forcedChangeColor: true,
  },
  sensors: {
    motionTrackerMode: true,
    motionTrackerRange: true,
  },
} as const satisfies ToCapabilities<PlayerTraits>;

export const CAPABILITES_73 = {
  ir: {
    gameVariant: {
      baseVariant: {
        metadata: true,
        builtIn: true,
        teamScoringMethod: true,
        miscellaneousOptions: {
          teamsEnabled: true,
          roundResetPlayers: true,
          roundResetMap: true,
          perfectionEnabled: false,
          roundTimeLimitMinutes: true,
          roundCount: true,
          earlyVictoryWinCount: true,
          suddenDeathTimeLimitSeconds: true,
          gracePeriodTimeLimitSeconds: true,
        },
        respawnOptions: {
          inheritRespawnTime: true,
          respawnWithTeammate: true,
          respawnAtLocation: true,
          respawnOnKills: true,
          livesPerRound: true,
          teamLivesPerRound: true,
          respawnTimeSeconds: true,
          suicidePenaltySeconds: true,
          betrayalPenaltySeconds: true,
          respawnGrowthSeconds: true,
          loadoutCamTime: true,
          respawnPlayerTraitsDurationSeconds: true,
          respawnPlayerTraits: CAPABILITIES_73_PLAYER_TRAITS,
        },
        socialOptions: {
          friendlyFireEnabled: true,
          betrayalBootingEnabled: true,
          enemyVoiceEnabled: true,
          openChannelVoiceEnabled: true,
          deadPlayerVoiceEnabled: true,
        },
        mapOverrideOptions: {
          grenadesOnMap: true,
          shortcutsOnMap: true,
          equipmentOnMap: true,
          powerupsOnMap: true,
          turretsOnMap: true,
          indestructibleVehicles: true,
          basePlayerTraits: CAPABILITIES_73_PLAYER_TRAITS,
          weaponSetAbsoluteIndex: true,
          vehicleSetAbsoluteIndex: true,
          redPowerupTraits: CAPABILITIES_73_PLAYER_TRAITS,
          bluePowerupTraits: CAPABILITIES_73_PLAYER_TRAITS,
          yellowPowerupTraits: CAPABILITIES_73_PLAYER_TRAITS,
          redPowerupDurationSeconds: true,
          bluePowerupDurationSeconds: true,
          yellowPowerupDurationSeconds: true,
        },
        teamOptions: {
          model: true,
          designatorSwitchType: true,
          teams: {
            name: true,
            designator: true,
            model: true,
            teamColor: true,
            fireteamCount: true,
          },
        },
        loadoutTraits: {
          spartanLoadoutsEnabled: true,
          eliteLoadoutsEnabled: true,
          loadoutPalettes: {
            loadouts: {
              name: true,
              initialPrimaryWeaponAbsoluteIndex: true,
              initialSecondaryWeaponAbsoluteIndex: true,
              initialEquipmentAbsoluteIndex: true,
              initialGrenadeCountSetting: true,
            },
          },
        },
      },
      playerTraits: {
        name: true,
        description: true,
        traits: CAPABILITIES_73_PLAYER_TRAITS,
      },
      userDefinedOptions: true,
      scriptStrings: true,
      baseNameStringIndex: true,
      localizedName: true,
      localizedDescription: true,
      localizedCategory: false,
      engineIcon: true,
      engineCategory: false,
      mapPermissions: false,
      playerRatings: {
        ratingScale: false,
        killWeight: false,
        assistWeight: false,
        betrayalWeight: false,
        deathWeight: false,
        normalizeByMaxKills: false,
        base: false,
        range: false,
        lossScalar: false,
        customStat0: false,
        customStat1: false,
        customStat2: false,
        customStat3: false,
        expansion0: false,
        expansion1: false,
        showInScoreboard: false,
      },
      scoreToWinRound: true,
      fireTeamsEnabled: false,
      symmetricGametype: true,
      baseVariantParametersLocked: false,
      baseVariantParametersHidden: false,
      tu1Settings: {
        alwaysSpilloverDamage: false,
        armorLockStickiesRemain: false,
        attachedDamageBypassShields: false,
        activeCamoOverrideEnergyCurve: false,
        swordGunClangKills: false,
        magnumIsAutomatic: false,
        precisionBloom: false,
        armorLockDamageDrain: false,
        armorLockDamageDrainLimit: false,
        activeCamoEnergyCurveMin: false,
        activeCamoEnergyCurveMax: false,
        magnumDamage: false,
        magnumFireDelay: false,
      },
    },
  },
} as const satisfies CompilerCapabilities;
