import {
  type CompilerCapabilities,
  type ToCapabilities,
} from "src/backend/compile/diagnostics/assertCompatibleIR";
import type { PlayerTraits } from "src/frontend/intermediate-representation/game/game_engine_player_traits";

const CAPABILITIES_107_MCC_PLAYER_TRAITS = {
  shieldVitality: {
    damageResistancePercentage: true,
    bodyMultiplierPercentage: true,
    bodyRechargeRatePercentage: true,
    shieldMultiplierPercentage: true,
    shieldRechargeRatePercentage: true,
    headshotImmunity: true,
    vampirismPercentage: true,
    assasinationImmunity: true,
    deathless: true,
  },
  weapons: {
    damageModifierPercentageSetting: true,
    meleeDamageModifierPercentageSetting: true,
    initialPrimaryWeaponAbsoluteIndex: true,
    initialSecondaryWeaponAbsoluteIndex: true,
    initialGrenadeCount: true,
    rechargingGrenades: true,
    infiniteAmmo: true,
    weaponPickup: true,
    equipmentUsage: true,
    dropEquipment: true,
    infiniteEquipment: true,
    initialEquipmentAbsoluteIndex: true,
  },
  movement: {
    speedPercentage: true,
    gravityPercentage: true,
    vehicleUsage: true,
    jumpModifier: true,
    // Reach megalo ≤ 73 only; not in the TU1 trait layout
    sprinting: false,
  },
  appearance: {
    activeCamo: true,
    waypoint: true,
    gamertag: true,
    forcedChangeColor: true,
  },
  sensors: {
    motionTrackerMode: true,
    motionTrackerRange: true,
  },
} as const satisfies ToCapabilities<PlayerTraits>;

export const CAPABILITES_107_MCC = {
  ir: {
    gameVariant: {
      baseVariant: {
        metadata: true,
        builtIn: true,
        teamScoringMethod: true,
        miscellaneousOptions: {
          teamsEnabled: true,
          roundResetPlayers: true,
          roundResetMap: true,
          perfectionEnabled: true,
          roundTimeLimitMinutes: true,
          roundCount: true,
          earlyVictoryWinCount: true,
          suddenDeathTimeLimitSeconds: true,
          gracePeriodTimeLimitSeconds: true,
        },
        respawnOptions: {
          inheritRespawnTime: true,
          respawnWithTeammate: true,
          respawnAtLocation: true,
          respawnOnKills: true,
          livesPerRound: true,
          teamLivesPerRound: true,
          respawnTimeSeconds: true,
          suicidePenaltySeconds: true,
          betrayalPenaltySeconds: true,
          respawnGrowthSeconds: true,
          loadoutCamTime: true,
          respawnPlayerTraitsDurationSeconds: true,
          respawnPlayerTraits: CAPABILITIES_107_MCC_PLAYER_TRAITS,
        },
        socialOptions: {
          friendlyFireEnabled: true,
          betrayalBootingEnabled: true,
          enemyVoiceEnabled: true,
          openChannelVoiceEnabled: true,
          deadPlayerVoiceEnabled: true,
        },
        mapOverrideOptions: {
          grenadesOnMap: true,
          shortcutsOnMap: true,
          equipmentOnMap: true,
          powerupsOnMap: true,
          turretsOnMap: true,
          indestructibleVehicles: true,
          basePlayerTraits: CAPABILITIES_107_MCC_PLAYER_TRAITS,
          weaponSetAbsoluteIndex: true,
          vehicleSetAbsoluteIndex: true,
          redPowerupTraits: CAPABILITIES_107_MCC_PLAYER_TRAITS,
          bluePowerupTraits: CAPABILITIES_107_MCC_PLAYER_TRAITS,
          yellowPowerupTraits: CAPABILITIES_107_MCC_PLAYER_TRAITS,
          redPowerupDurationSeconds: true,
          bluePowerupDurationSeconds: true,
          yellowPowerupDurationSeconds: true,
        },
        teamOptions: {
          model: true,
          designatorSwitchType: true,
          teams: {
            name: true,
            designator: true,
            model: true,
            teamColor: true,
            fireteamCount: true,
          },
        },
        loadoutTraits: {
          spartanLoadoutsEnabled: true,
          eliteLoadoutsEnabled: true,
          loadoutPalettes: {
            loadouts: {
              name: true,
              initialPrimaryWeaponAbsoluteIndex: true,
              initialSecondaryWeaponAbsoluteIndex: true,
              initialEquipmentAbsoluteIndex: true,
              initialGrenadeCountSetting: true,
            },
          },
        },
      },
      playerTraits: {
        name: true,
        description: true,
        traits: CAPABILITIES_107_MCC_PLAYER_TRAITS,
      },
      userDefinedOptions: true,
      scriptStrings: true,
      baseNameStringIndex: true,
      localizedName: true,
      localizedDescription: true,
      localizedCategory: true,
      engineIcon: true,
      engineCategory: true,
      mapPermissions: true,
      playerRatings: {
        ratingScale: true,
        killWeight: true,
        assistWeight: true,
        betrayalWeight: true,
        deathWeight: true,
        normalizeByMaxKills: true,
        base: true,
        range: true,
        lossScalar: true,
        customStat0: true,
        customStat1: true,
        customStat2: true,
        customStat3: true,
        expansion0: true,
        expansion1: true,
        showInScoreboard: true,
      },
      scoreToWinRound: true,
      fireTeamsEnabled: true,
      symmetricGametype: true,
      baseVariantParametersLocked: true,
      baseVariantParametersHidden: true,
      tu1Settings: {
        alwaysSpilloverDamage: true,
        armorLockStickiesRemain: true,
        attachedDamageBypassShields: true,
        activeCamoOverrideEnergyCurve: true,
        swordGunClangKills: true,
        magnumIsAutomatic: true,
        precisionBloom: true,
        armorLockDamageDrain: true,
        armorLockDamageDrainLimit: true,
        activeCamoEnergyCurveMin: true,
        activeCamoEnergyCurveMax: true,
        magnumDamage: true,
        magnumFireDelay: true,
      },
    }
  }
 } as const satisfies CompilerCapabilities;

